Timestamp in embeds and raise error in commands
ZeusAbhijeet/SleepBot pull request #12
Opened 2021-02-12 15:24 UTC by Amey-wale

Added timestamps in embeds and added raise error in errors of commands link clear messages, ban, kick so that any unknown error can be seen in the terminal !.

its_charmander

2021-02-12 15:30 UTC, ZeusAbhijeet commented on Rule.py
> +				timestamp=ctx.message.created_at)
timestamps not required for this one because it won't suit it.

2021-02-12 15:31 UTC, ZeusAbhijeet commented on Util.py
> +		timestamp=ctx.message.created_at
Logs already have the time the command was run so not required

2021-02-12 15:32 UTC, ZeusAbhijeet commented on CodeHelp.py
> +                    timestamp=ctx.message.created_at
Timestamps won't work out for this embed because page number will overwrite it

2021-02-12 15:37 UTC, ZeusAbhijeet requested changes
Remove the timestamps where I have added comments in `CodeHelp.py`, `Rule.py` and `Util.py` because they either don't suit, won't show up or are already there in some other form

2021-02-13 09:10 UTC, Amey-wale commented on CodeHelp.py
> +                    timestamp=ctx.message.created_at
I have edited the files , I had committed them too, you can check !

2021-02-14 06:29 UTC, Amey-wale commented
Updated the files

2021-02-14 10:16 UTC, merged